changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🌟 Features
      labels:
        - feature
    - title: 🐞 Bug Fixes
      labels:
        - bug
    - title: Others
      labels:
        - chore