name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version tag
        if: startsWith( github.ref, 'refs/tags/v' )
        run: echo ${{ github.ref }}
        env:
          REF: ${{ github.ref }}
      - name: Create Github Release
        run: gh release create ${{ github.ref }} --draft --generate-notes